# Generated by Django 4.2.2 on 2023-06-20 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import resume.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название резюме",
                        max_length=1000,
                        verbose_name="Название резюме",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Введите номер телефона",
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите email",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "portfolio",
                    models.URLField(
                        blank=True,
                        help_text="Введите ссылку на портфолио",
                        null=True,
                        verbose_name="Ссылка на портфолио",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("intern", "интерн"),
                            ("junior", "джуниор"),
                            ("middle", "миддл"),
                            ("senior", "сеньор"),
                            ("lead", "лид"),
                        ],
                        help_text="Выберите грейд",
                        max_length=200,
                        verbose_name="Грейд",
                    ),
                ),
                (
                    "salary",
                    models.IntegerField(
                        blank=True,
                        help_text="Выберите заработную плату",
                        null=True,
                        verbose_name="Заработная плата",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("secondary", "среднее"),
                            ("special_secondary", "среднее специальное"),
                            ("unfinished_higher", "неоконченное высшее"),
                            ("higher", "высшее"),
                            ("bachelor", "бакалавр"),
                            ("master", "магистр"),
                            ("candidate", "кандидат наук"),
                            ("doctor", "доктор наук"),
                        ],
                        help_text="Выберите образование",
                        max_length=200,
                        null=True,
                        verbose_name="Образование",
                    ),
                ),
                (
                    "experience",
                    models.TextField(
                        blank=True,
                        help_text="Расскажите о вашем опыте работы",
                        max_length=200,
                        null=True,
                        verbose_name="Опыт работы",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("frontend", "фронтенд"),
                            ("backend", "бэкенд"),
                            ("gamedev", "геймдев"),
                            ("devops", "девопс"),
                            ("design", "дизайн"),
                            ("products", "продукты"),
                            ("management", "менеджмент"),
                            ("testing", "тестирование"),
                        ],
                        help_text="Выберите специальность",
                        null=True,
                        verbose_name="Специальность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_published", "не опубликовано"),
                            ("published", "опубликовано"),
                            ("blocked", "заблокировано"),
                            ("on_moderation", "на модерации"),
                        ],
                        default=resume.models.Status["not_published"],
                        help_text="Выберите статус",
                        max_length=200,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Выберите владельца резюме",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец резюме",
                    ),
                ),
            ],
            options={
                "verbose_name": "Резюме",
                "verbose_name_plural": "Резюме",
            },
        ),
    ]
