version: '3'
services:
  db:
    restart: always
    image: postgres
    container_name: resume_db
    env_file: sky_test/.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
