version: '3'

services:
  db:
    restart: always
    image: postgres
    container_name: resume_db
    env_file:
      - sky_test/.env
    expose:
      - '5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U app -d resume_db' ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./sky_test:/sky_test
      - static_value:/sky_test/static/
      - media_value:/sky_test/media/
    expose:
      - '8000'
    depends_on:
      - db
    env_file:
      - sky_test/.env
    logging:
      driver: 'local'
      options:
        max-size: '10m'
        max-file: '3'

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    ports:
      - '80:80'

volumes:
  postgres_data:
  static_value:
  media_value:
